const data = {
    categories: [
      { id: 1, name: 'Form or Checklist' },
      { id: 2, name: 'Document' },
      { id: 3, name: 'Track a Date' },
    ],
    subCategories: [
      { id: 1, name: 'Crew', categoryId: 1 },
      { id: 2, name: 'Engineering', categoryId: 1 },
      { id: 3, name: 'Permits to Work', categoryId: 1 },
      { id: 4, name: 'Security', categoryId: 1 },
      { id: 5, name: 'SMS', categoryId: 1 },
      { id: 6, name: 'Class', categoryId: 2 },
      { id: 7, name: 'Crew', categoryId: 2 },
      { id: 8, name: 'Equipment', categoryId: 2 },
      { id: 9, name: 'Flag', categoryId: 2 },
      { id: 10, name: 'Insurance', categoryId: 2 },
      { id: 11, name: 'Plans & Manuals', categoryId: 2 },
      { id: 12, name: 'SOP', categoryId: 2 },
      { id: 13, name: 'Risk Assessment', categoryId: 2 },
      { id: 14, name: 'MSDS', categoryId: 2 },
      { id: 15, name: 'Standing Orders', categoryId: 2 },
      { id: 16, name: 'Statutory', categoryId: 2 },
    ],
    items: [
      { id: 1, name: 'Seafarer Appraisal', subCategoryId: 1 },
      { id: 2, name: 'Familiarization - EOOW', subCategoryId: 1 },
      { id: 3, name: 'Familiarization - General', subCategoryId: 1 },
      { id: 4, name: 'Familiarization - OOW', subCategoryId: 1 },
      { id: 5, name: 'Familiarization - SMS', subCategoryId: 1 },
      { id: 6, name: 'Familiarization - Cyber Security', subCategoryId: 1 },
      { id: 7, name: 'New Crew Checklist', subCategoryId: 1 },
      { id: 8, name: 'Medical History', subCategoryId: 1 },
      { id: 9, name: 'Crew Departure Checklist', subCategoryId: 1 },
      { id: 10, name: 'Declaration of Medical Care Person in Charge', subCategoryId: 1 },
      { id: 11, name: 'Declaration of Ship Safety Officer', subCategoryId: 1 },
      { id: 12, name: 'Declaration of Ship Security Officer', subCategoryId: 1 },
      { id: 13, name: 'Bunker Checklist', subCategoryId: 2 },
      { id: 14, name: 'Note of Protest', subCategoryId: 2 },
      { id: 15, name: 'Sludge Disposal Checklist', subCategoryId: 2 },
      { id: 16, name: 'Working Aloft', subCategoryId: 3 },
      { id: 17, name: 'Hot Work', subCategoryId: 3 },
      { id: 18, name: 'Underwater Operations', subCategoryId: 3 },
      { id: 19, name: 'Electrical Maintenance or Repair', subCategoryId: 3 },
      { id: 20, name: 'Entry into Enclosed Spaces', subCategoryId: 3 },
      { id: 21, name: 'Working over the Side', subCategoryId: 3 },
      { id: 22, name: 'Declaration of Security', subCategoryId: 4 },
      { id: 23, name: 'Ship Security Plan Annual Review', subCategoryId: 4 },
      { id: 24, name: 'Report of Security Incident', subCategoryId: 4 },
      { id: 25, name: 'Security Level Checklist', subCategoryId: 4 },
      { id: 26, name: 'SSAS Testing Procedures', subCategoryId: 4 },
      { id: 27, name: 'Security Items Inspection Checklist', subCategoryId: 4 },
      { id: 28, name: 'Changing Watch (Bridge)', subCategoryId: 5 },
      { id: 29, name: 'Changing Watch (Engineering)', subCategoryId: 5 },
      { id: 30, name: 'Passage Plan', subCategoryId: 5 },
      { id: 31, name: 'Pre-Arrival Checklist (Deck)', subCategoryId: 5 },
      { id: 32, name: 'Pre-Arrival Checklist (Engineering)', subCategoryId: 5 },
      { id: 33, name: 'Pre-Departure Checklist (Deck)', subCategoryId: 5 },
      { id: 34, name: 'Pre-Departure Checklist (Engineering)', subCategoryId: 5 },
      { id: 35, name: 'LSA & FFE Quarterly Maintenance & Inspections', subCategoryId: 5 },
      { id: 36, name: 'LSA & FFE Annual Maintenance & Inspections', subCategoryId: 5 },
      { id: 37, name: 'LSA & FFE Monthly Maintenance & Inspections', subCategoryId: 5 },
      { id: 38, name: 'LSA & FFE Weekly Maintenance & Inspections', subCategoryId: 5 },
      { id: 39, name: 'Drill Report - Fire', subCategoryId: 5 },
      { id: 40, name: 'Drill Report - Abandon Ship', subCategoryId: 5 },
      { id: 41, name: 'Drill Report - Steering', subCategoryId: 5 },
      { id: 42, name: 'Drill Report - Other', subCategoryId: 5 },
      { id: 43, name: 'Accident, Near Miss, or Damage', subCategoryId: 5 },
      { id: 44, name: 'Safety Meeting Report', subCategoryId: 5 },
      { id: 45, name: 'Handover - Chief Engineer', subCategoryId: 5 },
      { id: 46, name: 'Handover - Master', subCategoryId: 5 },
      { id: 47, name: 'Handover - Chief Officer', subCategoryId: 5 },
      { id: 48, name: 'Handover - Safety Officer', subCategoryId: 5 },
      { id: 49, name: 'Handover - Security Officer', subCategoryId: 5 },
      { id: 50, name: 'Non Conformity Report', subCategoryId: 5 },
      { id: 51, name: 'Class Certificate', subCategoryId: 6 },
      { id: 52, name: 'Class Agreement', subCategoryId: 6 },
      { id: 53, name: 'International Tonnage Certificate', subCategoryId: 16 },
      { id: 54, name: 'International Air Pollution Prevention Certificate', subCategoryId: 16 },
      { id: 55, name: 'International Oil Pollution Prevention Certificate', subCategoryId: 16 },
      { id: 56, name: 'International Sewage Pollution Prevention Certificate', subCategoryId: 16 },
      { id: 57, name: 'International Energy Efficiency Certificate', subCategoryId: 16 },
      { id: 58, name: 'International Anti-Fouling System Certificate', subCategoryId: 16 },
      { id: 59, name: 'SOLAS Safety Construction Certificate', subCategoryId: 16 },
      { id: 60, name: 'SOLAS Safety Equipment Certificate', subCategoryId: 16 },
      { id: 61, name: 'SOLAS Safety Radio Certificate', subCategoryId: 16 },
      { id: 62, name: 'International Load Line Certificate', subCategoryId: 16 },
      { id: 63, name: 'Maritime Labour Convention Certificate', subCategoryId: 16 },
      { id: 64, name: 'DMLC Part I', subCategoryId: 16 },
      { id: 65, name: 'DMLC Part II', subCategoryId: 16 },
      { id: 66, name: 'Certificate of Competency', subCategoryId: 7 },
      { id: 67, name: 'Certificate of Endorsement', subCategoryId: 7 },
      { id: 68, name: 'Basic Safety Training', subCategoryId: 7 },
      { id: 69, name: 'Medical Certificate', subCategoryId: 7 },
      { id: 70, name: 'Life Raft Service Report', subCategoryId: 8 },
      { id: 71, name: 'Portable Fire Extinguisher Service Report', subCategoryId: 8 },
      { id: 72, name: 'SCBA Service Report', subCategoryId: 8 },
      { id: 73, name: 'Immersion Suit Service Report', subCategoryId: 8 },
    { id: 74, name: 'Inflatable Life Jacket Service Report', subCategoryId: 8 },
    { id: 75, name: 'Certificate of Registry', subCategoryId: 9 },
    { id: 76, name: 'Tax Receipt', subCategoryId: 9 },
    { id: 77, name: 'Charter Certificate', subCategoryId: 9 },
    { id: 78, name: 'Radio Station License', subCategoryId: 9 },
    { id: 79, name: 'Civil Liability Bunker Convention Certificate', subCategoryId: 9 },
    { id: 80, name: 'Nairobi Wreck Removal Certificate', subCategoryId: 9 },
    { id: 81, name: 'P&I', subCategoryId: 10 },
    { id: 82, name: 'Hull & Machinery', subCategoryId: 10 },
    { id: 83, name: 'Pollution', subCategoryId: 10 },
    { id: 84, name: 'Civil Liability Bunker Convention - Blue Card', subCategoryId: 10 },
    { id: 85, name: 'Nairobi Wreck Removal - Blue Card', subCategoryId: 10 },
    { id: 86, name: 'SOLAS Safety Training Manual', subCategoryId: 11 },
    { id: 87, name: 'Safety Management System Manual', subCategoryId: 11 },
    { id: 88, name: 'Garbage Management Plan', subCategoryId: 11 },
    { id: 89, name: 'Mooring & Towing Arrangement', subCategoryId: 11 },
    { id: 90, name: 'Energy Efficiency Management Plan', subCategoryId: 11 },
    { id: 91, name: 'Rescue of Persons from Sea', subCategoryId: 11 }
    ],
    };

    export default data;
